#!/bin/bash

export DESKTOP_CORE_NAME="vscode"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v1.75.1
export DESKTOP_CORE_ORG="microsoft"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/vscode/releases/download"
